title: Badminton Championships 2024
email: contact@badmintonevent.com
description: >
  Welcome to the official website of the Badminton Championships 2024. Join us to witness top players from around the globe compete for the championship title!

baseurl: ""  # Leave empty if the site is at the root of the domain.
url: "http://www.badmintonevent.com"  # The base hostname & protocol for your site.

twitter_username: badmintonevent2024
github_username: badmintonevent

# Build settings
theme: minima
minima:
  skin: "air"  # Using the 'air' skin for a lighter theme, suitable for sports event aesthetics.

plugins:
  - jekyll-feed  # Enables RSS feed

# SEO Plugin for enhancing visibility
  - jekyll-seo-tag

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Additional theme settings to improve aesthetics
sass:
  style: compressed  # Minimizes CSS for faster loading times

# Navigation settings
navigation:
  - title: "Schedule"
    url: /schedule/
  - title: "About"
    url: /about/
  - title: "Contact"
    url: /contact/

# Adding Google Analytics for tracking (replace with your actual tracking ID)
google_analytics: UA-XXXXX-Y
